# Generated by Django 4.0.8 on 2023-01-16 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_remove_member_has_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, choices=[('suz', 'Suzuki'), ('yam', 'Yamaha'), ('har', 'Harley Davidson')], max_length=3)),
                ('model', models.CharField(max_length=120)),
                ('production_year', models.PositiveSmallIntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=(2010, 2010))),
                ('color', models.CharField(default='White', max_length=20)),
                ('seats', models.PositiveSmallIntegerField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'ordering': ['brand', 'production_year'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, choices=[('for', 'Ford'), ('fia', 'Fiat'), ('toy', 'Toyota'), ('kia', 'Kia'), ('peu', 'Peugeot'), ('cit', 'Citroen'), ('che', 'Chevrolet')], default='for', max_length=3)),
                ('model', models.CharField(max_length=120)),
                ('production_year', models.PositiveSmallIntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2010)),
                ('color', models.CharField(default='White', max_length=20)),
                ('seats', models.PositiveSmallIntegerField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'ordering': ['brand', 'production_year'],
            },
        ),
    ]
