# Generated by Django 4.1.5 on 2023-01-19 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0002_remove_member_has_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motorcycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("suzu", "Suzuki"),
                            ("yama", "Yamaha"),
                            ("harl", "Harley Davidson"),
                        ],
                        max_length=4,
                    ),
                ),
                ("model", models.CharField(max_length=120)),
                (
                    "production_year",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2010, 2010),
                            (2011, 2011),
                            (2012, 2012),
                            (2013, 2013),
                            (2014, 2014),
                            (2015, 2015),
                            (2016, 2016),
                            (2017, 2017),
                            (2018, 2018),
                            (2019, 2019),
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                        ],
                        default=(2010, 2010),
                    ),
                ),
                ("color", models.CharField(default="White", max_length=20)),
                ("seats", models.PositiveSmallIntegerField(default=1)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.member"
                    ),
                ),
            ],
            options={
                "ordering": ["brand", "production_year"],
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ford", "Ford"),
                            ("fiat", "Fiat"),
                            ("toyo", "Toyota"),
                            ("kia", "Kia"),
                            ("peug", "Peugeot"),
                            ("citr", "Citroen"),
                            ("chev", "Chevrolet"),
                        ],
                        default="ford",
                        max_length=4,
                    ),
                ),
                ("model", models.CharField(max_length=120)),
                (
                    "production_year",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2010, 2010),
                            (2011, 2011),
                            (2012, 2012),
                            (2013, 2013),
                            (2014, 2014),
                            (2015, 2015),
                            (2016, 2016),
                            (2017, 2017),
                            (2018, 2018),
                            (2019, 2019),
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                        ],
                        default=2010,
                    ),
                ),
                ("color", models.CharField(default="White", max_length=20)),
                ("seats", models.PositiveSmallIntegerField(default=1)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("air_condition", models.BooleanField(default=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.member"
                    ),
                ),
            ],
            options={
                "ordering": ["brand", "production_year"],
            },
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.UniqueConstraint(
                condition=models.Q(("production_year__lte", 2016)),
                fields=("member", "brand"),
                name="unique_car_brand_and_memeber",
                violation_error_message="You can add only one old car within car brand. Old <= 2016.",
            ),
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gte", models.F("start_date"))),
                name="check_start_and_end_date",
                violation_error_message="Start date must be before end date.",
            ),
        ),
    ]
