# Generated by Django 4.0.8 on 2023-01-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='air_condition',
            field=models.BooleanField(default=True),
        ),
    ]
