# Generated by Django 4.0.8 on 2023-01-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_car_air_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, choices=[('ford', 'Ford'), ('fiat', 'Fiat'), ('toyota', 'Toyota'), ('kia', 'Kia'), ('peugeot', 'Peugeot'), ('citroen', 'Citroen'), ('chevrolet', 'Chevrolet')], default='ford', max_length=20),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='brand',
            field=models.CharField(blank=True, choices=[('suzuki', 'Suzuki'), ('yamaha', 'Yamaha'), ('harley-davidson', 'Harley Davidson')], max_length=20),
        ),
    ]
