# Generated by Django 4.0.8 on 2023-01-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_car_brand_alter_motorcycle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, choices=[('ford', 'Ford'), ('fiat', 'Fiat'), ('toyo', 'Toyota'), ('kia', 'Kia'), ('peug', 'Peugeot'), ('citr', 'Citroen'), ('chev', 'Chevrolet')], default='ford', max_length=4),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='brand',
            field=models.CharField(blank=True, choices=[('suzu', 'Suzuki'), ('yama', 'Yamaha'), ('harl', 'Harley Davidson')], max_length=4),
        ),
    ]
