# Generated by Django 4.1.5 on 2023-01-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_remove_car_check_air_condition"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="car",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("air_condition", True), ("color__iexact", "black")),
                    models.Q(("color__iexact", "black"), _negated=True),
                    _connector="OR",
                ),
                name="check_air_condition2",
                violation_error_message="Black cars must have air condition.",
            ),
        ),
    ]
