# Generated by Django 4.1.5 on 2023-01-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_alter_car_brand_alter_motorcycle_brand"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="car",
            constraint=models.UniqueConstraint(
                fields=("member", "brand"),
                name="unique_car_brand_and_memeber",
                violation_error_message="Only VIP members can lend more than one car in each Brand!",
            ),
        ),
    ]
