# Generated by Django 4.1.5 on 2023-01-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0005_car_unique_car_brand_and_memeber"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="car",
            name="unique_car_brand_and_memeber",
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.UniqueConstraint(
                fields=("member", "brand"),
                name="unique_car_brand_and_memeber2",
                violation_error_message="Only VIP members can lend more than one car in each Brand!",
            ),
        ),
    ]
