# Generated by Django 4.1.5 on 2023-01-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0006_car_check_air_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorcycle",
            name="brand",
            field=models.CharField(
                blank=True,
                choices=[
                    ("suzu", "Suzuki"),
                    ("yama", "Yamaha"),
                    ("harl", "Harley Davidson"),
                ],
                default="suzu",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="motorcycle",
            name="production_year",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                    (2023, 2023),
                ],
                default=2010,
            ),
        ),
    ]
