# Generated by Django 4.1.5 on 2023-01-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0017_remove_car_unique_car_brand_and_memeber_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="car",
            name="unique_car_brand_and_memeber",
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.UniqueConstraint(
                condition=models.Q(("member__is_vip", False)),
                fields=("member", "brand"),
                name="unique_car_brand_and_memeber",
                violation_error_message="You can add only one old car within car brand. Old <= 2016.",
            ),
        ),
    ]
