# Generated by Django 4.1.5 on 2023-01-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0018_car_end_date_car_start_date_motorcycle_end_date_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="car",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gte", models.F("start_date"))),
                name="check_car_dates",
                violation_error_message="End date must be after start date",
            ),
        ),
    ]
