# Generated by Django 4.1.5 on 2023-01-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0024_motorcycle_end_date_motorcycle_start_date"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="car",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gte", models.F("start_date"))),
                name="check_start_and_end_date",
                violation_error_message="Start date must be before end date.",
            ),
        ),
    ]
